# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby-version: [2.3.0, 2.4.4, 2.5.5, 2.6.3]
        appraisal: ["3.2", "4.0", "4.1", "4.2", "5.0", "5.1", "5.2", "6.0"]
        include:
          - ruby-version: 2.7.5
            appraisal: "7.0"
          - ruby-version: 3.3.5
            appraisal: "8.0"
        exclude:
          - ruby-version: 2.3.0
            appraisal: "4.2"
          - ruby-version: 2.3.0
            appraisal: "6.0"
          - ruby-version: 2.4.4
            appraisal: "3.2"
          - ruby-version: 2.4.4
            appraisal: "4.0"
          - ruby-version: 2.4.4
            appraisal: "4.1"
          - ruby-version: 2.4.4
            appraisal: "4.2"
          - ruby-version: 2.4.4
            appraisal: "6.0"
          - ruby-version: 2.5.5
            appraisal: "3.2"
          - ruby-version: 2.5.5
            appraisal: "4.0"
          - ruby-version: 2.5.5
            appraisal: "4.1"
          - ruby-version: 2.5.5
            appraisal: "4.2"
          - ruby-version: 2.6.3
            appraisal: "3.2"
          - ruby-version: 2.6.3
            appraisal: "4.0"
          - ruby-version: 2.6.3
            appraisal: "4.1"
          - ruby-version: 2.6.3
            appraisal: "4.2"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          rubygems: default
          bundler: none
      - name: Install compatible bundler for all envs
        run: gem install bundler -v 1.17.3
      - name: Bundle for Appraisal
        run: bundle
      - name: Install Appraisal dependencies
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle
      - name: Run tests
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle exec rake test
